In [1]:
# Q1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
# Ans>>
import numpy as np

arr = np.arange(0,6)
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int64


In [ ]:
# Q2. Given a NumPy array 'arr', check if its data type is float64.
#  arr = np.array([1.5,2.6,3.7])
# Ans>> import numpy as np
arr = np.array([1.5,2.6,3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)

True


In [ ]:
# Q 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
# Ans>> import numpy as np
arr = np.array([4+6j,2+4j,6+12j],dtype=np.complex128)
print(arr)
print(arr.dtype)

[4. +6.j 2. +4.j 6.+12.j]
complex128


In [ ]:
# Q 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
# Ans >> import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)



[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float32


In [ ]:
# Q 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
# Ans>>  import numpy as np
arr = np.array([1.123456789, 2.123456789, 3.123456789])
print(arr)
print(arr.dtype)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)

[1.12345679 2.12345679 3.12345679]
float64
[1.1234568 2.1234567 3.1234567]
float32


In [ ]:
# Q 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
import numpy as np

def array_attributes(arr):

  shape = arr.shape
  size = arr.size
  data_type = arr.dtype

  return shape, size, data_type
arr = np.array([[1, 2, 3], [4, 5, 6]])

shape, size, data_type = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", data_type)

Shape: (2, 3)
Size: 6
Data type: int64


In [ ]:
# Q 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
# ans >>
import numpy as np

def array_dimension(arr):
    return arr.ndim

# Example usage:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Dimensionality of arr_1d:", array_dimension(arr_1d))
print("Dimensionality of arr_2d:", array_dimension(arr_2d))
print("Dimensionality of arr_3d:", array_dimension(arr_3d))




Dimensionality of arr_1d: 1
Dimensionality of arr_2d: 2
Dimensionality of arr_3d: 3


In [ ]:
# Q 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
# ans >>
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = item_size * arr.size
    return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
item_size, total_size = item_size_info(arr)
print("Item size:", item_size, "bytes")
print("Total size:", total_size, "bytes")


Item size: 8 bytes
Total size: 72 bytes


In [ ]:
# Q 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
# ans>>
import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array strides:", array_strides(arr))


Array strides: (24, 8)


In [ ]:
# Q 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
# ans>>
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape, strides = shape_stride_relationship(arr)
print("Array shape:", shape)
print("Array strides:", strides)



Array shape: (3, 3)
Array strides: (24, 8)


In [ ]:
# Q 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
# Ans>>
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [ ]:
# Q 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
# Ans>>
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Q 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

# Ans >>
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(0, 10, 1))
print(generate_range_array(0, 10, 2))
print(generate_range_array(1, 11, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]


In [ ]:
# Q  14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally
#  spaced values between `start` and `stop`

# Ans >>
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print(generate_linear_space(0, 1, 5))


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
# Ans >>
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 16 Q. Write a function that takes a Python list and converts it into a NumPy array.
# ans >>
import numpy as np

def list_to_numpy_array(py_list):
    np_array = np.array(py_list)
    return np_array

# Example usage
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)


[1 2 3 4 5]


In [ ]:
# 17 Q.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
# Ans >>
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new array object that views the same data
view_array = original_array.view()

# Print the original array and the view array
print("Original array:", original_array)
print("View array:", view_array)

# Modify an element in the view array
view_array[0] = 99

# Print both arrays to show that they share the same data
print("\nAfter modifying the view array:")
print("Original array:", original_array)
print("View array:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]

After modifying the view array:
Original array: [99  2  3  4  5]
View array: [99  2  3  4  5]


In [ ]:
# 18.Q  Write a function that takes two NumPy arrays and concatenates them along a specified axis.
# ans >>
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along the first axis (rows)
concatenated_array_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along the second axis (columns)
concatenated_array_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", concatenated_array_1)


Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# 19.Q  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
# Ans>>
import numpy as np

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

# Ensure the arrays have the same number of rows
assert array1.shape[0] == array2.shape[0], "Arrays must have the same number of rows to concatenate horizontally."

# Concatenate the arrays horizontally
concatenated_array = np.concatenate((array1, array2), axis=1)

# Print the concatenated array
print("Concatenated array (horizontally):\n", concatenated_array)


Concatenated array (horizontally):
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
# 20.Q Write a function that vertically stacks multiple NumPy arrays given as a list
# Ans >>
import numpy as np

def vertical_stack_arrays(array_list):
    stacked_array = np.vstack(array_list)
    return stacked_array

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

# List of arrays to be stacked
arrays_to_stack = [array1, array2, array3]

# Vertically stack the arrays
stacked_array = vertical_stack_arrays(arrays_to_stack)

# Print the stacked array
print("Vertically stacked array:\n", stacked_array)


Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# Q.21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
# ans >.
import numpy as np

def create_integer_array(start, stop, step):
    # Use np.arange() to generate the array, ensuring the stop value is inclusive
    return np.arange(start, stop + 1, step)

# Example usage
start = 1
stop = 10
step = 2

integer_array = create_integer_array(start, stop, step)
print("Array of integers:", integer_array)


Array of integers: [1 3 5 7 9]


In [ ]:
# 22.Q Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
# Ans>>
import numpy as np

def generate_equally_spaced_values(start, stop, num_values):
    return np.linspace(start, stop, num_values)

# Example usage
start = 0
stop = 1
num_values = 10

equally_spaced_values = generate_equally_spaced_values(start, stop, num_values)
print("Equally spaced values:", equally_spaced_values)


Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 23.Q Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
# Ans>.
import numpy as np

def generate_logarithmically_spaced_values(start, stop, num_values):
    return np.logspace(np.log10(start), np.log10(stop), num_values)

# Example usage
start = 1
stop = 1000
num_values = 5

logarithmically_spaced_values = generate_logarithmically_spaced_values(start, stop, num_values)
print("Logarithmically spaced values:", logarithmically_spaced_values)



Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24.Q . Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
# ans>.
import numpy as np
import pandas as pd

def create_random_dataframe(rows, columns, low, high):
    # Generate a NumPy array with random integers
    random_array = np.random.randint(low, high, size=(rows, columns))

    # Create a DataFrame using the random array
    df = pd.DataFrame(random_array, columns=[f'Column_{i+1}' for i in range(columns)])

    return df

# Example usage
rows = 5
columns = 3
low = 1
high = 101

random_dataframe = create_random_dataframe(rows, columns, low, high)
print(random_dataframe)


   Column_1  Column_2  Column_3
0        15        79        35
1        75        74        27
2        66        65        41
3        51        39        37
4        16         9        17


In [ ]:
# 25. Q  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    # Ensure the column exists in the DataFrame
    if column_name in df.columns:
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        raise ValueError(f"Column '{column_name}' does not exist in the DataFrame.")

    return df

# Example usage
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [10, -20, 30, -40, 50]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zero(df, 'B')

print("\nModified DataFrame (with negatives in column 'B' replaced by zeros):")
print(df)


Original DataFrame:
   A  B   C
0  1 -1  10
1 -2  2 -20
2  3 -3  30
3 -4  4 -40
4  5 -5  50

Modified DataFrame (with negatives in column 'B' replaced by zeros):
   A  B   C
0  1  0  10
1 -2  2 -20
2  3  0  30
3 -4  4 -40
4  5  0  50


In [ ]:
# 26.Q  Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
# Ans>>
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("3rd element of the array:", third_element)


3rd element of the array: 30


In [ ]:
#27.Q Retrieve the element at index (1, 2) from the 2D NumPy array
# arr_2d = np.array([[1, 2, 3],
#                [4, 5, 6],
#                [7, 8, 9]])
# ans>.
import numpy as np

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Access the element at index (1, 2)
element_at_index_1_2 = arr_2d[1, 2]

print("Element at index (1, 2):", element_at_index_1_2)




Element at index (1, 2): 6


In [ ]:
# 28. Q Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])
# ans>>
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask to identify elements greater than 5
mask = arr > 5

# Use the boolean mask to extract elements greater than 5
elements_greater_than_5 = arr[mask]

print("Elements greater than 5:", elements_greater_than_5)



Elements greater than 5: [ 8 10  7]


In [ ]:
# 29. Q Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Ans>>
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
# 30.Q Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# arr_2d = np.array([[1, 2, 3],
#                   [4, 5, 6],
#                   [7, 8, 9]])
# Ans>>
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the 2D array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)



Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


In [ ]:
# 31.Q Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
# ans>>
import numpy as np

def extract_elements_with_indices(arr_2d, indices):
    # Flatten the 2D array and then use fancy indexing to extract elements based on indices
    return arr_2d.flatten()[indices]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([4, 1, 6, 2, 7, 5])  # Example indices

extracted_elements = extract_elements_with_indices(arr_2d, indices)
print("Extracted elements based on provided indices:", extracted_elements)


Extracted elements based on provided indices: [5 2 7 3 8 6]


In [ ]:
# 32.Q Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
# Ans>>
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    # Create a boolean mask to identify elements greater than the threshold
    mask = arr > threshold

    # Use the boolean mask to filter elements
    filtered_array = arr[mask]

    return filtered_array

# Example usage
arr = np.array([1, 5, 10, 15, 20, 25])
threshold = 10

filtered_elements = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", filtered_elements)


Filtered elements greater than 10 : [15 20 25]


In [ ]:
# 33.Q Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
# ans>>
import numpy as np

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    # Use the provided indices to extract elements from the 3D array
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]

    return extracted_elements

# Example usage
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                    [[7, 8, 9], [10, 11, 12]]])

indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([1, 0])
indices_dim3 = np.array([2, 1])

extracted_elements = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:", extracted_elements)



Extracted elements: [6 8]


In [ ]:
# 34.Q  Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
# Ans>>
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    # Use boolean indexing to filter elements where both conditions are satisfied
    filtered_array = arr[np.logical_and(condition1, condition2)]

    return filtered_array

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6])
condition1 = arr > 2
condition2 = arr % 2 == 0

filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)
print("Filtered elements satisfying both conditions:", filtered_elements)




Filtered elements satisfying both conditions: [4 6]


In [ ]:
# 35.Q Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
# ans>>
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    # Use the provided row and column indices to extract elements from the 2D array
    extracted_elements = arr_2d[row_indices, col_indices]

    return extracted_elements

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [2 4 9]


In [ ]:
# 36.Q Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
# ans>>>
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element using broadcasting
result = arr + 5

print("Original array:")
print(arr)
print("\nArray after adding 5 to each element:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
# 37.Q Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
# ans>>
import numpy as np

# Create arr1 and arr2
arr1 = np.random.randint(1, 10, size=(1, 3))
arr2 = np.random.randint(1, 10, size=(3, 4))

# Print original arrays
print("arr1:")
print(arr1)
print("arr2:")
print(arr2)

# Reshape arr1 to (3, 1) to broadcast across the rows of arr2
arr1_reshaped = arr1.reshape(3, 1)

# Perform the multiplication using broadcasting
result = arr2 * arr1_reshaped

# Print the result
print("Result of multiplying each row of arr2 by the corresponding element in arr1:")
print(result)




arr1:
[[9 5 6]]
arr2:
[[7 7 1 7]
 [6 1 3 1]
 [1 9 1 2]]
Result of multiplying each row of arr2 by the corresponding element in arr1:
[[63 63  9 63]
 [30  5 15  5]
 [ 6 54  6 12]]


In [5]:
# 38.Q  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
# ans>>
import numpy as np

# Create arr1 and arr2
arr1 = np.random.randint(0, 10, size=(1, 4))
arr2 = np.random.randint(0, 10, size=(4, 3))

# Print original arrays
print("arr1:")
print(arr1)
print("arr2:")
print(arr2)

# Transpose arr2 to make the shapes compatible for broadcasting
arr2_transposed = arr2.T

# Add arr1 to each column of arr2_transposed (effectively adding to each row of arr2)
result_transposed = arr2_transposed + arr1

# Transpose the result back to original shape
result = result_transposed.T

# Print the result
print("Result of adding arr1 to each row of arr2:")
print(result)


arr1:
[[1 8 4 5]]
arr2:
[[6 4 1]
 [5 6 5]
 [0 4 9]
 [2 6 8]]
Result of adding arr1 to each row of arr2:
[[ 7  5  2]
 [13 14 13]
 [ 4  8 13]
 [ 7 11 13]]


In [ ]:
# 39 Q Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
# ans>>
import numpy as np

# Create arr1 of shape (3, 1) and arr2 of shape (1, 3)
arr1 = np.array([[1],
                  [2],
                  [3]])
arr2 = np.array([[4, 5, 6]])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


arr1:
[[1]
 [2]
 [3]]

arr2:
[[4 5 6]]

Result of element-wise addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [4]:
# 40.Q Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
# ans>>
import numpy as np

# Create arr1 and arr2
arr1 = np.random.randint(0, 10, size=(2, 3))
arr2 = np.random.randint(0, 10, size=(2, 2))

# Print original arrays
print("arr1:")
print(arr1)
print("arr2:")
print(arr2)

# Expand arr2 to shape (2, 3) by repeating the last column
arr2_expanded = np.hstack([arr2, arr2[:, -1].reshape(2, 1)])

# Print expanded arr2
print("Expanded arr2:")
print(arr2_expanded)

# Perform element-wise multiplication using broadcasting
result = arr1 * arr2_expanded

# Print the result
print("Result of element-wise multiplication:")
print(result)



arr1:
[[7 4 7]
 [3 7 2]]
arr2:
[[2 1]
 [1 5]]
Expanded arr2:
[[2 1 1]
 [1 5 5]]
Result of element-wise multiplication:
[[14  4  7]
 [ 3 35 10]]


In [ ]:
# 41.Q Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# Ans>>
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_means = np.mean(arr, axis=0)

print("Array:")
print(arr)
print("\nColumn-wise mean:")
print(column_means)


Array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


In [ ]:
# 42.Q Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# ans>>
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find maximum value in each row
max_in_each_row = np.max(arr, axis=1)

print("Array:")
print(arr)
print("\nMaximum value in each row:")
print(max_in_each_row)


Array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


In [ ]:
# 43.Q  For the given array, find indices of maximum value in each column.
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# ans>>
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
max_indices_in_each_column = np.argmax(arr, axis=0)

print("Array:")
print(arr)
print("\nIndices of maximum value in each column:")
print(max_indices_in_each_column)



Array:
[[1 2 3]
 [4 5 6]]

Indices of maximum value in each column:
[1 1 1]


In [ ]:
# 44.Q For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# ans>>
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Custom function to calculate moving sum along rows
def moving_sum(row):
    return np.convolve(row, np.ones(2), mode='valid')

# Apply the custom function along rows
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Array:")
print(arr)
print("\nMoving sum along rows:")
print(moving_sum_result)


Array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows:
[[ 3.  5.]
 [ 9. 11.]]


In [ ]:
# 45.Q  In the given array, check if all elements in each column are even.
# arr = np.array([[2, 4, 6], [3, 5, 7]])
# ans>>
import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
are_all_even = np.all(arr % 2 == 0, axis=0)

print("Array:")
print(arr)
print("\nAre all elements in each column even?")
print(are_all_even)


Array:
[[2 4 6]
 [3 5 7]]

Are all elements in each column even?
[False False False]


In [ ]:
# 46.Q  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])
#ans>>
import numpy as np

def reshape_array(original_array, m, n):
    reshaped_matrix = np.reshape(original_array, (m, n))
    return reshaped_matrix

# Given NumPy array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a matrix of dimensions m rows and n columns
m = 2  # Number of rows
n = 3  # Number of columns
reshaped_matrix = reshape_array(original_array, m, n)

print("Original array:")
print(original_array)
print("\nReshaped matrix:")
print(reshaped_matrix)


Original array:
[1 2 3 4 5 6]

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [ ]:
# 47.Q Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
#ans>>
import numpy as np

def flatten_matrix(input_matrix):
    flattened_array = input_matrix.flatten()  # or input_matrix.ravel()
    return flattened_array

# Given input matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Flatten the input matrix
flattened_array = flatten_matrix(input_matrix)

print("Input matrix:")
print(input_matrix)
print("\nFlattened array:")
print(flattened_array)


Input matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


In [ ]:
# 48.Q Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])
#ans>>
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Given arrays
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

# Concatenate the arrays along the default axis (axis=0)
concatenated_array_axis0 = concatenate_arrays(array1, array2)

# Concatenate the arrays along the specified axis (axis=1)
concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated array along axis 0:")
print(concatenated_array_axis0)
print("\nConcatenated array along axis 1:")
print(concatenated_array_axis1)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 49.Q . Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# ans>>
import numpy as np

def split_array(original_array, num_splits, axis=0):
    sub_arrays = np.split(original_array, num_splits, axis=axis)
    return sub_arrays

# Given original array
original_array = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

# Split the original array into multiple sub-arrays along the default axis (axis=0)
num_splits = 3
sub_arrays_axis0 = split_array(original_array, num_splits)

# Split the original array into multiple sub-arrays along the specified axis (axis=1)
sub_arrays_axis1 = split_array(original_array, num_splits, axis=1)

print("Original array:")
print(original_array)
print("\nSub-arrays along axis 0:")
for sub_array in sub_arrays_axis0:
    print(sub_array)
print("\nSub-arrays along axis 1:")
for sub_array in sub_arrays_axis1:
    print(sub_array)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-arrays along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Sub-arrays along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [ ]:
# 50.Q Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]
#ans>>
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)

    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)

    return original_array

# Given data
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Insert and delete elements
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:")
print(original_array)
print("\nModified array:")
print(modified_array)


Original array:
[1 2 3 4 5]

Modified array:
[ 1 10 11  4  5]


In [3]:
# 51.Q Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
# Ans>>
import numpy as np

# Step 2: Create arr1 with random integers
arr1 = np.random.randint(0, 100, size=10)  # Random integers between 0 and 99, array of size 10

# Step 3: Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)  # Integers from 1 to 10

# Step 4: Perform element-wise addition
result = np.add(arr1, arr2)

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)



arr1: [95 30 44 34 54 90 47 79 16 92]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition result: [ 96  32  47  38  59  96  54  87  25 102]


In [7]:
# 52.Q . Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
# ans>>
import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of subtracting arr2 from arr1:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of subtracting arr2 from arr1: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [8]:
# 53.Q Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
# ans>>
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 10, size=5)  # Random integers between 1 and 9, array of size 5

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)


arr1: [6 8 6 4 5]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 6 16 18 16 25]


In [9]:
# 54.Q. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
# ans>>
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # [2, 4, 6, 8, 10]

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [10]:
#55.Q Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
# ans>>
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)  # [1, 2, 3, 4, 5]

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]  # [5, 4, 3, 2, 1]

# Perform element-wise exponentiation
result = np.power(arr1, arr2)

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


In [11]:
# 56.QWrite a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
# ans>>
import numpy as np

def count_substring_occurrences(arr, substring):
    count = 0
    for string in arr:
        count += string.count(substring)
    return count

# Example array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Example usage
substring = 'hello'
result = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' occurs {result} times in the array.")


The substring 'hello' occurs 3 times in the array.


In [12]:
# Q57.Write a function that extracts uppercase characters from a NumPy array of strings.arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
# ans>>
import numpy as np

def extract_uppercase_characters(arr):
    uppercase_characters = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_characters.append(char)
    return uppercase_characters

# Example array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Example usage
result = extract_uppercase_characters(arr)
print("Uppercase characters extracted:", result)


Uppercase characters extracted: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [13]:
# 58.Q  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# ans>>
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    replaced_array = np.copy(arr)  # Create a copy of the original array to avoid modifying it directly
    for i, string in enumerate(replaced_array):
        replaced_array[i] = string.replace(old_substring, new_substring)
    return replaced_array

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Example usage
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)
print("Array after replacement:", result)


Array after replacement: ['orange' 'banana' 'grape' 'pineorang']


In [14]:
# 59.Q  Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])
# ans>>
import numpy as np

def concatenate_strings_element_wise(arr1, arr2):
    concatenated_array = np.empty_like(arr1)  # Create an empty array with the same shape as arr1
    for i in range(len(arr1)):
        concatenated_array[i] = arr1[i] + arr2[i]
    return concatenated_array

# Example arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Example usage
result = concatenate_strings_element_wise(arr1, arr2)
print("Concatenated array:", result)


Concatenated array: ['Hello' 'World']


In [15]:
# 60.Q Write a function that finds the length of the longest string in a NumPy array.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
# ans>>
import numpy as np

def longest_string_length(arr):
    max_length = 0
    for string in arr:
        max_length = max(max_length, len(string))
    return max_length

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Example usage
result = longest_string_length(arr)
print("Length of the longest string:", result)


Length of the longest string: 9


In [16]:
# 61.Q  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
# ans>>
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(dataset)

# Compute the median
median = np.median(dataset)

# Compute the variance
variance = np.var(dataset)

# Compute the standard deviation
std_deviation = np.std(dataset)

# Print the results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [861 889 416  19  84 804 271 610 721 504 372 480 154  23 928 346 945 109
  70 606 720 215 305 756 242 399  99 252 154  47 681 479 236 234 631 251
 733 774 847 636 561 818 935 609 791 417 747 825 226 111 248 896 551 696
 279 352 667 301 400 945 837 361 604 712 848 870 695  92 995 189 260 384
 992 577  24 379 584  44 484 345 675 895 540 374 446 250 234 858 864 905
 647  10 840 715 975 112 916 771   7 626]
Mean: 512.14
Median: 545.5
Variance: 86411.14039999999
Standard Deviation: 293.9577187283913


In [17]:
# 62.Q Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
# ans>.
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the percentiles
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


25th percentile: 27.5
75th percentile: 68.25


In [18]:
# Q 63.Q Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
# ans>>
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.random.rand(50)
array2 = np.random.rand(50)

# Compute the correlation coefficient between the arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

# Print the correlation coefficient
print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: -0.07051773828014092


In [19]:
# 64.Q  Create two matrices and perform matrix multiplication using NumPy's `dot` function.
# ans>>
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the result
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [20]:
# 65.Q Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
# ans>>
import numpy as np

# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1001, size=50)

# Calculate the percentiles and quartiles
percentiles = np.percentile(array, [10, 25, 50, 75, 90])

# Print the results
print("10th percentile:", percentiles[0])
print("First quartile (25th percentile):", percentiles[1])
print("Median (50th percentile):", percentiles[2])
print("Third quartile (75th percentile):", percentiles[3])
print("90th percentile:", percentiles[4])


10th percentile: 122.0
First quartile (25th percentile): 324.0
Median (50th percentile): 516.0
Third quartile (75th percentile): 671.0
90th percentile: 878.8000000000001


In [21]:
#66.Q Create a NumPy array of integers and find the index of a specific element.
# ans>>
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element (e.g., 30)
# Method 1: Using np.where()
index1 = np.where(arr == 30)[0]

# Method 2: Using array indexing
index2 = np.argmax(arr == 30)

# Print the index
print("Index of the element 30 (using np.where()):", index1)
print("Index of the element 30 (using array indexing):", index2)


Index of the element 30 (using np.where()): [2]
Index of the element 30 (using array indexing): 2


In [23]:
# 67.Q Generate a random NumPy array and sort it in ascending order.
# ans>>
import numpy as np

# Generate a random NumPy array of shape (5, ) with values between 0 and 1
random_array = np.random.rand(10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Print the original and sorted arrays
print("Original array:", random_array)
print("Sorted array in ascending order:", sorted_array)


Original array: [5.20849154e-01 6.44842297e-03 2.83643023e-01 7.22803699e-01
 4.88488982e-01 5.52703792e-01 9.54642395e-01 6.58053167e-01
 4.75349157e-04 5.77492656e-01]
Sorted array in ascending order: [4.75349157e-04 6.44842297e-03 2.83643023e-01 4.88488982e-01
 5.20849154e-01 5.52703792e-01 5.77492656e-01 6.58053167e-01
 7.22803699e-01 9.54642395e-01]


In [24]:
# 68.Q Filter elements >20  in the given NumPy array.
# r = np.array([12, 25, 6, 42, 8, 30])
# ans>>
import numpy as np

# Given NumPy array
r = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = r[r > 20]

# Print the filtered array
print("Elements greater than 20:", filtered_array)


Elements greater than 20: [25 42 30]


In [25]:
# 69.Q Filter elements which are divisible by 3 from a given NumPy array.
# arr = np.array([1, 5, 8, 12, 15])
# ans>.
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

# Print the filtered array
print("Elements divisible by 3:", filtered_array)


Elements divisible by 3: [12 15]


In [27]:
# 70.Q Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements greater than or equal to 20 and less than or equal to 40
filtered_array = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Elements between 20 and 40 (inclusive):", filtered_array)



Elements between 20 and 40 (inclusive): [20 30 40]


In [28]:
# 71.Q  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte Order:", byte_order)


Byte Order: =


In [29]:
# 72. Q For the given NumPy array, perform byte swapping in place using `byteswap()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the modified array
print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [30]:
# 73.Q For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the original and swapped arrays
print("Original array:", arr)
print("Array after byte order swap:", swapped_arr)


Original array: [1 2 3]
Array after byte order swap: [16777216 33554432 50331648]


In [31]:
# 74. Q For the given NumPy array and swap its byte order conditionally based on system endianness using attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system endianness
system_endianness = arr.dtype.byteorder

# Swap byte order conditionally based on system endianness
if system_endianness != '=':
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

# Print the original and swapped arrays
print("Original array:", arr)
print("Array after conditional byte order swap based on system endianness:", swapped_arr)


Original array: [1 2 3]
Array after conditional byte order swap based on system endianness: [1 2 3]


In [33]:
# 75.Q For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)
# ans>>
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
byte_order = arr.dtype.byteorder
byte_swapping_needed = byte_order != '='

# Print the result
if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Byte swapping is not necessary for the current system.


In [34]:
# 76.Q Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
# ans>>
import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original array (arr1):", arr1)
print("Modified copy array (copy_arr):", copy_arr)



Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [35]:
# 77.Q Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
# ans>>
import numpy as np

# Create a 2D NumPy array of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice from the matrix
view_slice = matrix[:2, :2]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Print the original matrix and the modified slice
print("Original matrix:")
print(matrix)
print("\nModified slice:")
print(view_slice)


Original matrix:
[[100   2   1]
 [  5   2   6]
 [  9   3   1]]

Modified slice:
[[100   2]
 [  5   2]]


In [36]:
# 78.Q Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

# ans>>
import numpy as np

# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice from array_a
view_b = array_a[:2, :2]

# Broadcast the addition of 5 to view_b
view_b += 5

# Print the original array_a and the modified view_b
print("Original array_a:")
print(array_a)
print("\nModified view_b:")
print(view_b)


Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified view_b:
[[ 6  7]
 [ 9 10]]


In [37]:
# 79.Q Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

# ans>>
import numpy as np

# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Print the original orig_array and the modified reshaped_view
print("Original orig_array:")
print(orig_array)
print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[100   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [44]:
# 80.Q Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

# ans>>
import numpy as np

# Create a NumPy array of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 100

# Print both the original data and the modified data_copy
print("Original data:")
print(data)
print("\nModified data_copy:")
print(data_copy)


Original data:
[[5 9 5 5]
 [4 4 2 6]
 [8 4 8 7]]

Modified data_copy:
[100   6   8   8   7]


In [45]:
# 81.Q Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
# ans>>
import numpy as np

# Create matrices A and B with identical shape containing integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform addition between matrices A and B
addition_result = A + B

# Perform subtraction between matrices A and B
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition result:")
print(addition_result)
print("\nSubtraction result:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result:
[[ 8 10 12]
 [14 16 18]]

Subtraction result:
[[-6 -6 -6]
 [-6 -6 -6]]


In [46]:
# 82.Q Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
# ans>>
import numpy as np

# Generate matrices C (3x2) and D (2x4)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

# Print the result
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nMultiplication result:")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Multiplication result:
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [47]:
# 83.Q  Create a matrix `E` and find its transpose.
# ans>>
import numpy as np

# Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6]])

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)
print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [48]:
# 84.Q  Generate a square matrix `F` and compute its determinant.
# ans>>
import numpy as np

# Generate a square matrix F
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix F and its determinant
print("Matrix F:")
print(F)
print("\nDeterminant of matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


In [49]:
# 85.Q  Create a square matrix `G` and find its inverse.
# ans>>
import numpy as np

# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Find the inverse of matrix G
inverse_G = np.linalg.inv(G)

# Print the matrix G and its inverse
print("Matrix G:")
print(G)
print("\nInverse of matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
